-- MySQL Script generated by MySQL Workbench
-- mån 17 jul 2017 22:36:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mindlevel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mindlevel` ;

-- -----------------------------------------------------
-- Schema mindlevel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mindlevel` DEFAULT CHARACTER SET utf8 ;
USE `mindlevel` ;

-- -----------------------------------------------------
-- Table `mindlevel`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mindlevel`.`user` ;

CREATE TABLE IF NOT EXISTS `mindlevel`.`user` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `image` VARCHAR(255) NULL,
  `session` VARCHAR(255) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_active` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mindlevel`.`mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mindlevel`.`mission` ;

CREATE TABLE IF NOT EXISTS `mindlevel`.`mission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creator` VARCHAR(255) NOT NULL,
  `validated` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mission_user_idx` (`creator` ASC),
  CONSTRAINT `fk_mission_user`
    FOREIGN KEY (`creator`)
    REFERENCES `mindlevel`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mindlevel`.`accomplishment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mindlevel`.`accomplishment` ;

CREATE TABLE IF NOT EXISTS `mindlevel`.`accomplishment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `mission_id` INT NOT NULL,
  `score` INT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_accomplishment_mission_idx` (`mission_id` ASC),
  CONSTRAINT `fk_accomplishment_mission`
    FOREIGN KEY (`mission_id`)
    REFERENCES `mindlevel`.`mission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mindlevel`.`user_accomplishment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mindlevel`.`user_accomplishment` ;

CREATE TABLE IF NOT EXISTS `mindlevel`.`user_accomplishment` (
  `username` VARCHAR(255) NOT NULL,
  `accomplishment_id` INT NOT NULL,
  PRIMARY KEY (`username`, `accomplishment_id`),
  INDEX `fk_user_accomplishment_2_idx` (`accomplishment_id` ASC),
  CONSTRAINT `fk_user_accomplishment_1`
    FOREIGN KEY (`username`)
    REFERENCES `mindlevel`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_accomplishment_2`
    FOREIGN KEY (`accomplishment_id`)
    REFERENCES `mindlevel`.`accomplishment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
